# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
source 'https://github.com/CocoaPods/Specs.git'

inhibit_all_warnings!

target 'AppRTCDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AppRTCDemo
  pod 'SnapKit', '~> 5.0.0'
  pod 'GoogleWebRTC'
  pod 'SocketRocket'

end
